[package]
name = "chatot"
version = "0.1.0"
edition = "2018"
license-file = "LICENSE"
repository = "https://github.com/ShinySylveon04/PokemonRNGTools"
description = "wasm powering https://chatot.pokemonrng.com"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true
opt-level = 'z'

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_repr = "0.1"
wasm-bindgen = {version = "=0.2.78", features = ["serde-serialize"]}
wasm-bindgen-test = "0.2"
num_enum = "0.5"
js-sys = "0.3.55"
console_error_panic_hook = "0.1.7"
chatot_forms = { path = "../forms" }
